### ISSUE TITLE
RBAC example?

### ISSUE THREAD

**Issue by irlevesque** [mikkeloscar/kube-metrics-adapter#6]
I'm looking at incorporating this project into our cluster for some SQS-based HPA workloads. Do you have an example of what RBAC rules are required?

**Comment by mikkeloscar** [comment]
I don't have an RBAC example right now. It depends on which collectors are used but I'll try to come up with an example that covers all of the current collectors.

If you only need SQS for now, then I think the RBAC rules from the [/k8s-prometheus-adapter](https://github.com/DirectXMan12/k8s-prometheus-adapter/tree/master/deploy/manifests) are enough.

**Comment by mikkeloscar** [comment]
@irlevesque I have added RBAC config in #7. Let me know if it doesn't work for you.

**Comment by mikkeloscar** [comment]
This project is now moved to https://github.com/zalando-incubator/kube-metrics-adapter RBAC was added, please open an issue there if it doesn't work.
